CARD$P.variable = "variable"
CARD$P.unit = "unit"
CARD$P.is_date = FALSE
CARD$P.is_normalize = TRUE
CARD$P.palette = NULL
CARD$P.glose = "glose"
CARD$P.topic = "event"
CARD$P.sampling_period = NULL

CARD$P1.funct = NULL
CARD$P1.funct_args = NULL
CARD$P1.time_step = "year"
CARD$P1.sampling_period = NULL
CARD$P1.is_date = FALSE
CARD$P1.NApct_lim = NULL
CARD$P1.NAyear_lim = NULL
CARD$P1.Seasons = c("DJF", "MAM", "JJA", "SON")
CARD$P1.nameEX = "X"
CARD$P1.keep = NULL
CARD$P1.compress = FALSE
CARD$P1.expand = FALSE
CARD$P1.rmNApct = TRUE
